tartiflette/tartiflette

- .coveragerc
- .gitignore
- .gitmodules
- .style.yapf
- Makefile
- README.md
- pylintrc
- setup.py
- tartiflette/executors/basic.py
- tartiflette/hooks/__init__.py
- tartiflette/parser/__init__.py
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/exceptions.py
- tartiflette/parser/nodes/definition.py
- tartiflette/parser/nodes/field.py
- tartiflette/parser/nodes/fragment_definition.py
- tartiflette/parser/nodes/node.py
- tartiflette/parser/nodes/variable_definition.py
- tartiflette/parser/parser.py
- tartiflette/parser/visitor.py
- tartiflette/tartiflette.py
- tests/func/test_queries.py
- tests/func/utils.py
- tests/unit/test_parser.py
Still needed to be done :
* Support of FragmentDefinition/FragmentSpread :white_check_mark: 
* Support type condition in FragmentDefinition :white_check_mark:  
* Support Lists in the results. :white_check_mark: 
* Resolver results serializations. :white_check_mark: 
* Remove stupid jokes in code.
* Transform TODOs in issues (or do them).
* Refactor member accessors for classes. (I.E. make properties or everything public)
* Proper executor/execution interface/classes.
* Tests. Everywhere.
* Setup time compilation and cffi import of libgraphqlparser.
> First Code Dump.

- setup.py
- tartiflette/parser/visitor.py
> Better setup.py and fix the value vars validation

- .gitignore
- README.md
> chore(doc): Update readme.md

- Makefile
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/parser.py
- tartiflette/parser/visitor.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/test_issue21.py
> ISSUE-21 - Fixing argument/variable input values

- docs/API.md
> API Documentation : Make resolvers async

- README.md
- tartiflette/executors/types.py
- tartiflette/introspection.py
- tartiflette/parser/nodes/field.py
- tartiflette/schema.py
- tartiflette/types/enum.py
- tartiflette/types/field.py
- tartiflette/types/list.py
- tartiflette/types/non_null.py
- tartiflette/types/object.py
- tartiflette/types/scalar.py
- tartiflette/types/type.py
- tests/functional/test_introspection.py
- tests/functional/test_issue21.py
- tests/functional/test_queries.py
- tests/functional/types/test_scalar.py
- tests/unit/types/test_object.py
Closes #15 and closes #16. Also fixes #17.
> fix(introspection): Fixed introspection

- Makefile
- examples/aiohttp/requirements.txt
- examples/aiohttp/starwars/app.py
- examples/aiohttp/starwars/handlers/graphql.py
- examples/aiohttp/starwars/query.json
- examples/aiohttp/starwars/starwars/__init__.py
- examples/aiohttp/starwars/starwars/resolvers/resolvers.py
- examples/aiohttp/starwars/starwars/sdl/__init__.py
- examples/aiohttp/starwars/starwars/sdl/starwars.sdl
- examples/aiohttp/starwars/utils/signals.py
- tartiflette/executors/basic.py
- tartiflette/parser/nodes/field.py
- tartiflette/parser/visitor.py
This is just a simple integration of Tartiflette in aoihttp, in order to have a little "poc".
Unfortunately the state of the execution code this is not working.
To use `pip install -e . && pip install -r examples/aoihttp/requirements.txt && cd examples/aiohttp/starwars && python3 app.py`
Then  `cd examples/aiohttp/starwars && curl -kv -X POST -d @query.json localhost:8089` 
Next step, make the engine works again :p
> Add starwars based integration example

- tartiflette/sdl/builder.py
- tartiflette/sdl/transformers/cleaning_transformer.py
- tartiflette/sdl/transformers/schema_transformer.py
These are really minor and subjective, so feel free to ignore them or pick-and-choose.
> Minor style changes regarding Lark

- setup.py
- tartiflette/resolver/factory.py
> Correct some English errors

- CHANGELOG.md
- setup.py
Use a method that close the file after reading it for loading the long_description from README.md in setup.py
> Better read for README file in setup.py

- CHANGELOG.md
- setup.py
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/nodes/field.py
- tartiflette/parser/visitor.py
- tests/functional/test_queries.py
- tests/functional/types/test_union.py
Now Union are supported and works as expected.
> Add Union Support

- CHANGELOG.md
- tartiflette/parser/nodes/field.py
- tartiflette/parser/visitor.py
- tartiflette/resolver/factory.py
- tartiflette/types/helpers/__init__.py
- tartiflette/types/helpers/has_typename.py
- tartiflette/types/type.py
- tartiflette/types/union.py
- tests/functional/regressions/test_issue21.py
- tests/functional/regressions/test_issue70.py
- tests/unit/parser/test_visitor.py
- tests/unit/resolver/test_factory.py
With this PR:
* TypeCondition in field is better managed. Closes #70 
* Typename attribute is automatically set except inside Union
> Better management of Typename and TypeCondition

- CHANGELOG.md
- setup.py
- tartiflette/parser/visitor.py
- tests/functional/regressions/test_issue70.py
- tests/functional/regressions/test_issue71.py
- tests/functional/test_typename.py
- tests/functional/types/test_union.py
- tests/unit/parser/test_visitor.py
> Really Fix the fragment execution regression.

- CHANGELOG.md
- tartiflette/parser/visitor.py
- tartiflette/schema/schema.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/regressions/test_issue70.py
- tests/functional/regressions/test_issue79.py
- tests/unit/test_schema_unit.py
> Raise errors when fragment target unknown type

- CHANGELOG.md
- tartiflette/parser/visitor.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/regressions/test_issue79.py
- tests/functional/regressions/test_issue80.py
- tests/unit/parser/test_visitor.py
> Raise errors when defined fragment isn't used

- CHANGELOG.md
- tartiflette/parser/visitor.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/regressions/test_issue79.py
- tests/functional/regressions/test_issue82.py
- tests/unit/parser/test_visitor.py
> Raise errors when undefined fragment is used

- CHANGELOG.md
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/visitor.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/regressions/test_issue87.py
- tests/unit/parser/test_visitor.py
> Raise errors on subscription operations with multiple root field

- CHANGELOG.md
- tartiflette/parser/visitor/visitor.py
- tartiflette/parser/visitor/visitor_context.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/data/sdls/libraries.sdl
- tests/functional/regressions/test_issue21.py
- tests/functional/regressions/test_issue97.py
- tests/functional/test_queries.py
- tests/unit/parser/visitor/test_visitor.py
> Raise errors on undefined arguments on nodes or directives

- CHANGELOG.md
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/visitor/visitor.py
- tests/functional/regressions/test_issue103.py
> Process enum values

- CHANGELOG.md
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/visitor/visitor.py
- tests/functional/data/sdls/animals.sdl
- tests/functional/regressions/test_issue103.py
- tests/functional/regressions/test_issue105.py
- tests/functional/regressions/test_issue87.py
- tests/functional/types/test_directive.py
- tests/unit/parser/visitor/test_visitor.py
> Fragment spread processing isn't handled properly

- CHANGELOG.md
- setup.py
- tartiflette/parser/visitor/visitor.py
- tartiflette/parser/visitor/visitor_context.py
- tartiflette/types/argument.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/regressions/test_issue101.py
- tests/functional/regressions/test_issue105.py
- tests/functional/regressions/test_issue97.py
- tests/unit/parser/visitor/test_visitor.py
- tests/unit/parser/visitor/test_visitor_context.py
> Raise errors on missing required argument on field / directive

- CHANGELOG.md
- setup.py
- tartiflette/schema/registry.py
- tests/functional/data/splitted_graphql/author.graphql
- tests/functional/data/splitted_graphql/blog.graphql
- tests/functional/data/splitted_graphql/post.graphql
- tests/functional/data/splitted_graphql/query.graphql
- tests/functional/data/splitted_mixed/author.sdl
- tests/functional/data/splitted_mixed/blog.graphql
- tests/functional/data/splitted_mixed/post.graphql
- tests/functional/data/splitted_mixed/query.sdl
- tests/functional/data/splitted_mixed_sub_dir/author/author.sdl
- tests/functional/data/splitted_mixed_sub_dir/blog/blog.graphql
- tests/functional/data/splitted_mixed_sub_dir/post.graphql
- tests/functional/data/splitted_mixed_sub_dir/query.sdl
- tests/functional/test_engine.py
> Support .graphql file and subdir in sdl rootdir

- CHANGELOG.md
- setup.py
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/visitor/visitor.py
- tartiflette/types/exceptions/tartiflette.py
- tartiflette/types/field.py
- tests/functional/regressions/test_issue105.py
- tests/functional/regressions/test_issue109.py
- tests/functional/regressions/test_issue21.py
- tests/unit/parser/visitor/test_visitor.py
> ISSUE-109 - Now throw an error when SelectionSet are badly used

- CHANGELOG.md
- tartiflette/parser/nodes/argument.py
- tartiflette/parser/nodes/directive.py
- tartiflette/parser/visitor/visitor.py
- tartiflette/parser/visitor/visitor_context.py
- tartiflette/resolver/factory.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/data/sdls/animals.sdl
- tests/functional/regressions/test_issue99.py
- tests/unit/parser/visitor/test_visitor.py
- tests/unit/resolver/test_factory__resolver_executor.py
> Raise errors on non unique argument on same node / directive

- CHANGELOG.md
- setup.py
- tartiflette/engine.py
- tartiflette/executors/basic.py
- tartiflette/parser/nodes/operation_definition.py
- tartiflette/parser/parser.py
- tartiflette/parser/visitor/visitor.py
- tests/unit/executor/test_basic.py
- tests/unit/parser/visitor/test_visitor.py
> Execute top‐level mutation selection set serially

- README.md
> Update Roadmap part of readme

- CHANGELOG.md
- pylintrc
- setup.py
- tartiflette/resolver/factory.py
- tartiflette/schema/schema.py
- tests/unit/resolver/test_factory.py
- tests/unit/resolver/test_factory__resolver_executor.py
- tests/unit/test_engine.py
> Add default subscription resolver for subscription without dedicated resolver

- CHANGELOG.md
- setup.py
- tartiflette/parser/nodes/field.py
- tartiflette/resolver/factory.py
- tests/functional/regressions/test_issue126.py
- tests/functional/test_empty_value.py
- tests/functional/test_tartiflette.py
- tests/functional/types/exceptions/test_tartiflette_errors.py
- tests/unit/resolver/test_factory.py
> ISSUE-126: Don't execute child of a None result.

- CHANGELOG.md
- setup.py
- tartiflette/parser/visitor/list_value.py
- tartiflette/parser/visitor/object_value.py
- tartiflette/parser/visitor/visitor.py
- tartiflette/parser/visitor/visitor_context.py
- tests/functional/regressions/test_issue127.py
> ISSUE-127 - Add support for Object and List in Request Values.

- CHANGELOG.md
- setup.py
- tartiflette/directive/common.py
- tartiflette/directive/directive.py
- tartiflette/parser/nodes/field.py
- tartiflette/resolver/factory.py
- tartiflette/sdl/transformers/schema_transformer.py
- tartiflette/types/argument.py
- tartiflette/types/field.py
- tartiflette/utils/arguments.py
- tests/functional/regressions/test_issue133.py
- tests/functional/types/test_directive.py
- tests/unit/directives/test_common.py
- tests/unit/directives/test_directive.py
- tests/unit/resolver/test_factory.py
- tests/unit/resolver/test_factory__resolver_executor.py
- tests/unit/types/test_argument.py
- tests/unit/types/test_input_object.py
- tests/unit/utils/test_arguments.py
> Handle argument directives

- CHANGELOG.md
- setup.py
- tartiflette/engine.py
- tests/functional/regressions/test_issue140.py
- tests/functional/test_engine_modules/__init__.py
- tests/functional/test_engine_modules/non_init_resolver.py
- tests/functional/test_engine_modules/resolver.py
> ISSUE-140 - Add lazy import feature at engine init time

- CHANGELOG.md
- setup.py
- tartiflette/directive/common.py
- tests/functional/regressions/test_issue143.py
> ISSUE-143 Fix a bug in default implementation of on_introspection directive hook

- docs/api/engine.md
> Remove wrong @Mutation from documentation

- docs/api/directive.md
> Fix on_introspection example code in API doc

- CHANGELOG.md
- CONTRIBUTORS.md
- setup.py
- tartiflette/schema/schema.py
- tartiflette/utils/arguments.py
- tests/functional/regressions/test_issue127.py
- tests/functional/regressions/test_issue154.py
closes #154 
Also validate that an inputType is composed only of inputType.
> ISSUE-154 - Now validate InputType better

- CHANGELOG.md
- tartiflette/parser/nodes/field.py
- tartiflette/types/exceptions/tartiflette.py
- tartiflette/utils/arguments.py
- tartiflette/utils/errors.py
- tests/functional/regressions/test_issue133.py
- tests/functional/regressions/test_issue139.py
- tests/unit/resolver/test_factory__resolver_executor.py
> Handle multiple exceptions

- CHANGELOG.md
- tartiflette/parser/cffi/__init__.py
- tests/functional/regressions/test_issue163.py
> ISSUE-163: Fix parsing of inline fragment without a type condition

- CHANGELOG.md
- setup.py
- tartiflette/directive/__init__.py
- tartiflette/directive/include.py
- tartiflette/directive/skip.py
- tartiflette/executors/basic.py
- tartiflette/parser/nodes/field.py
- tartiflette/parser/visitor/visitor.py
- tartiflette/parser/visitor/visitor_context.py
- tartiflette/resolver/factory.py
- tartiflette/schema/builtins/directives.sdl
- tartiflette/sdl/grammar/graphql_sdl_grammar.lark
- tartiflette/types/directive.py
- tartiflette/types/exceptions/tartiflette.py
- tests/functional/regressions/test_issue101.py
- tests/functional/regressions/test_issue158.py
- tests/functional/regressions/test_issue92.py
- tests/functional/test_introspection.py
- tests/unit/executor/test_basic.py
- tests/unit/parser/visitor/test_visitor.py
> ISSUE-158 - Add support for Query Directives

- CHANGELOG.md
- tartiflette/schema/schema.py
- tests/functional/regressions/test_issue160.py
> ISSUE-160 - Schema Validation now return all errors.

- README.md
> Add link to introduction blogpost

- CHANGELOG.md
- CONTRIBUTORS.md
- changelogs/0.6.8.md
- changelogs/next.md
- docs/CONTRIBUTING.md
- docs/PULL_REQUEST_TEMPLATE.md
- setup.py
> Release 0.6.8

- CHANGELOG.md
- Makefile
- changelogs/0.6.9.md
- setup.py
This should enable travis to push tag to our repository.
> Fix git-tag makefile rule

- changelogs/0.6.10.md
- setup.py
I hope this is right one. Now travis has the correct token with the correct set of rights
> Release 0.6.10

- changelogs/next.md
- tartiflette/__init__.py
- tests/functional/types/test_scalar.py
closes #179 
I am not sure if I should change the imports in tests to cover this. Happy to hear opinions!
> Expose Scalar in the root level

- changelogs/0.7.1.md
- changelogs/next.md
- setup.py
- tartiflette/utils/coercer.py
- tests/functional/regressions/test_issue188.py
Closes #188.
@tsunammis should we wait for https://github.com/dailymotion/tartiflette/pull/189 to be merged to test the release with Github actions?
> Fixing `KeyError` exception raised on nullable input fields not filled in

- CHANGELOG.md
- changelogs/0.8.2.md
- setup.py
- tartiflette/utils/arguments.py
- tartiflette/utils/coercer.py
- tests/functional/regressions/test_issue205.py
> Fix input object argument coerce

- CHANGELOG.md
- changelogs/0.8.3.md
- setup.py
- tartiflette/engine.py
- tartiflette/parser/nodes/variable_definition.py
- tartiflette/parser/visitor/visitor.py
- tests/functional/regressions/test_issue207.py
- tests/unit/parser/nodes/test_node_variabledefinition.py
- tests/unit/parser/visitor/test_visitor.py
> Handle properly argument default value on variable

- CHANGELOG.md
- changelogs/0.8.4.md
- setup.py
- tartiflette/engine.py
- tartiflette/parser/nodes/field.py
- tartiflette/utils/errors.py
- tests/functional/regressions/test_issue209.py
> Fix exception raised in arguments coercer

- CHANGELOG.md
- changelogs/0.8.6.md
- changelogs/next.md
- setup.py
- tartiflette/schema/registry.py
- tests/functional/regressions/sdl/issue201.sdl
- tests/functional/regressions/test_issue201.py
> ISSUE-201 - Now loaded SDLs are no more "onelined"

- CHANGELOG.md
- changelogs/0.8.7.md
- setup.py
- tartiflette/parser/cffi/__init__.py
- tartiflette/parser/visitor/visitor.py
- tests/functional/regressions/test_issue213.py
- tests/functional/regressions/test_null_nullable.py
- tests/unit/parser/visitor/test_visitor.py
> Handle properly null values on arguments & variables

- CHANGELOG.md
- changelogs/0.8.9.md
- setup.py
- tartiflette/types/argument.py
- tartiflette/types/list.py
- tartiflette/types/non_null.py
- tartiflette/types/type.py
- tartiflette/utils/arguments.py
- tartiflette/utils/coercer.py
- tests/functional/regressions/test_issue218.py
> ISSUE-218 - Fix input coercion of inputobject inside a non-null list

- CHANGELOG.md
- changelogs/0.10.1.md
- setup.py
- tartiflette/types/enum.py
- tests/functional/regressions/test_issue_233.py
> Handle input coercion on enum list

- changelogs/0.11.0.md
- changelogs/next.md
- docs/api-aiohttp/getting-started.md
- docs/api/directive.md
- docs/api/engine.md
- docs/api/error-handling.md
- docs/api/execution.md
- docs/api/scalar.md
- docs/api/schema-registry.md
- docs/api/subscription.md
- docs/plugin/introduction.md
- setup.py
- tartiflette/engine.py
Update the documentation on the new tremendous features developed by @abusi and @Maximilien-R about the "plugin" approach of tartiflette.
Close #237
> ISSUE-237: Documentation: Add new API of Engine() and create_engine()

- docs/tutorial/write-your-resolvers.md
Fixup minor typo in tutorial.
* [-] Update changelogs/next.md with your change (include reference to the issue & this PR).
* [-] Make sure all of the significant new logic is covered by tests.
* [-] Make sure all quality checks are green _[(Gazr specification)](https://gazr.io)_.
> Minor typo in write-your-resolvers.md

- CHANGELOG.md
- changelogs/0.11.2.md
- setup.py
- tartiflette/engine.py
- tests/unit/test_engine.py
> Return to a more flexible engine interface.

- changelogs/next.md
- tartiflette/schema/registry.py
- tartiflette/sdl/transformers/cleaning_transformer.py
- tests/functional/regressions/sdl/issue245.sdl
- tests/functional/regressions/test_issue245.py
> ISSUE-245 - Fix unicode sdl parsing.

- changelogs/next.md
- tartiflette/engine.py
- tests/unit/test_engine.py
> Make .cook() idempotent

- changelogs/next.md
- tartiflette/schema/registry.py
- tests/unit/conftest.py
> Add SchemaRegistry.clean()

- CHANGELOG.md
- changelogs/0.12.0.md
- changelogs/next.md
- setup.py
- tartiflette/directive/builtins/non_introspectable.py
- tartiflette/schema/registry.py
- tests/functional/regressions/test_issue92.py
- tests/functional/test_introspection.py
Release 0.12.0 because we have breaking changes in the import order of public classes.
> Prepare 0.12.0 Release

- CHANGELOG.md
- changelogs/0.12.3.md
- setup.py
- tartiflette/parser/visitor/visitor.py
- tests/functional/regressions/test_issue263.py
> ISSUE-267: Allow for empty list for [type!] to considered as valid inputs

- changelogs/1.0.0.md
- tartiflette/schema/schema.py
- tartiflette/schema/transformer.py
- tartiflette/types/enum.py
- tartiflette/types/input_object.py
- tartiflette/types/interface.py
- tartiflette/types/object.py
- tartiflette/types/scalar.py
- tartiflette/types/schema_extension.py
- tartiflette/types/type.py
- tartiflette/types/union.py
- tests/functional/regressions/issue278/test_issue278_extend_enum.py
- tests/functional/regressions/issue278/test_issue278_extend_input_object.py
- tests/functional/regressions/issue278/test_issue278_extend_interface.py
- tests/functional/regressions/issue278/test_issue278_extend_object.py
- tests/functional/regressions/issue278/test_issue278_extend_scalar.py
- tests/functional/regressions/issue278/test_issue278_extend_schema.py
- tests/functional/regressions/issue278/test_issue278_extend_union.py
> Support Extend schema syntax

- changelogs/1.0.0.md
- changelogs/next.md
- setup.py
- tartiflette/schema/bakery.py
- tartiflette/schema/registry.py
- tartiflette/schema/schema.py
- tests/functional/regressions/test_issue292.py
- tests/unit/test_schema_unit.py
> Bakes schema objects after extensions baking

- .github/workflows/push.yml
- README.md
- changelogs/1.0.0.md
- setup.py
- tartiflette/language/parsers/lark/transformers/converters.py
- tartiflette/language/parsers/lark/transformers/node_transformer.py
- tartiflette/language/validators/query/values_of_correct_type.py
- tartiflette/schema/schema.py
- tartiflette/utils/errors.py
> [Sonar] Fix some errors found by sonar

- docs/api/scalar.md
> Fix missing import in scalars example

- docs/migration-guides/migration-guide-0-0-to-1-0.md
- setup.py
> Prepare Release 1.0.0

- changelogs/next.md
- docs/tutorial/write-your-mutation-resolvers.md
> ISSUE-298 - Fix a condition in the tutorial

- changelogs/next.md
- tartiflette/engine.py
- tests/functional/regressions/test_issue309.py
> Take into account the `error_coercer` parameter at `Engine` initialization

- tartiflette/language/validators/query/argument_names.py
> Fix typo in error messages

- changelogs/next.md
- tartiflette/language/validators/query/all_variable_uses_defined.py
- tests/functional/validators/test_validators_all_variable_uses_defined.py
> chore(typo)

- tartiflette/utils/callables.py
- tests/unit/regressions/test_issue345.py
fixes #345 
We were forgetting is_method in the is_async_generator method
> ISSUE-345 - Forget the case when "generator" is a method

- CHANGELOG.md
- CONTRIBUTORS.md
- changelogs/1.1.2.md
- changelogs/next.md
- setup.py
- tartiflette/utils/callables.py
- tests/functional/regressions/test_issue105.py
- tests/functional/regressions/test_issue97.py
- tests/functional/validators/test_validators_all_variable_uses_defined.py
- tests/functional/validators/test_validators_input_object_field_uniqueness.py
- tests/unit/regressions/test_issue345.py
> Prepare the 1.1.2 Release.

- tartiflette/engine.py
> Fix some typos on engine function names

- changelogs/next.md
- tartiflette/types/enum.py
- tartiflette/types/input_object.py
- tartiflette/types/interface.py
- tartiflette/types/object.py
- tartiflette/types/scalar.py
- tartiflette/types/schema_extension.py
- tartiflette/types/union.py
> Fix comparison on extension types

- CHANGELOG.md
- CONTRIBUTORS.md
- changelogs/1.1.3.md
- changelogs/next.md
> Prepare 1.1.3 Release

- .github/workflows/on_pull_requests.yml
- .github/workflows/push_on_master.yml
- tartiflette/language/validators/__init__.py
- tartiflette/language/validators/query/values_of_correct_type.py
The Idea is to have:
- PR Event triggers a Tests,Style,Sonar + Publish to pypi-dev
- Push on master triggers a Tests,Style,Sonar+ Publish to pypi + Github Release
> Fix Sonar errors and Improve GithubActions Wkflow

- changelogs/next.md
- tartiflette/__init__.py
- tartiflette/engine.py
- tartiflette/execution/collect.py
- tartiflette/execution/context.py
- tests/functional/regressions/test_issue363.py
> ISSUE-363 - Custom query cache decorator

- changelogs/next.md
- docs/api/engine.md
- pylintrc
- tartiflette/__init__.py
- tartiflette/engine.py
- tartiflette/language/parsers/libgraphqlparser/parser.py
- tartiflette/schema/schema.py
- tests/functional/regressions/test_issue362.py
- tests/unit/regressions/test_issue362.py
> ISSUE-362 - Provide a way to use another json loader instead of the python one.

- changelogs/next.md
- docs/api/directive.md
- docs/api/engine.md
- docs/api/resolver.md
- docs/api/subscription.md
- tartiflette/__init__.py
- tartiflette/coercers/arguments.py
- tartiflette/coercers/inputs/list_coercer.py
- tartiflette/coercers/literals/list_coercer.py
- tartiflette/coercers/outputs/list_coercer.py
- tartiflette/directive/directive.py
- tartiflette/engine.py
- tartiflette/execution/execute.py
- tartiflette/resolver/default.py
- tartiflette/resolver/factory.py
- tartiflette/resolver/resolver.py
- tartiflette/schema/bakery.py
- tartiflette/schema/schema.py
- tartiflette/subscription/subscription.py
- tartiflette/types/directive.py
- tartiflette/types/field.py
- tartiflette/types/helpers/get_directive_instances.py
- tests/functional/regressions/test_issue361.py
> ISSUE-361 - Provide a way to override default callable used to coerce arguments

- changelogs/next.md
- tartiflette/schema/schema.py
- tests/functional/regressions/test_issue160.py
- tests/functional/regressions/test_issue370.py
> Fix Enum value uniqueness validation method

- changelogs/next.md
- tartiflette/schema/schema.py
- tartiflette/types/interface.py
- tests/functional/regressions/test_issue370.py
- tests/functional/regressions/test_issue372.py
Still need more tests cases, like union and so on.
closes #372
> ISSUE-372 - Validate ObjectFollowInterface better during SDL validation

- docs/tutorial/add-subscription.md
Minor improvements to grammar on the "Add subscription" tutorial page.
> docs: small grammar improvements for readability

- docs/api/engine.md
> Update docs showing error_coercer is async

- CHANGELOG.md
- changelogs/1.2.1.md
- setup.py
> 1.2.1 Release

- changelogs/1.2.0.md
> Wrong issue link for ISSUE-356

- CHANGELOG.md
> Wrong year in reference to v1.2.0

- tartiflette/resolver/resolver.py
- tartiflette/types/field.py
- tartiflette/types/object.py
- tests/functional/regressions/test_issue429.py
- tests/unit/test_resolver_decorator.py
> Allow usage of @Resolver on interface fields

- README.md
* ~~[ ] Update changelogs/next.md with your change (include reference to the issue & this PR).~~
* ~~[ ] Make sure all of the significant new logic is covered by tests.~~
* ~~[ ] Make sure all quality checks are green _[(Gazr specification)](https://gazr.io)_.~~
> fix(): readme typo

- changelogs/1.2.0.md
Update the changelog to describe the change to list coercion introduced in #367. This is a behavioural change, so it is appropriate to include it in the changelog.
---
> Update changelog for v1.2 to document change to output list coercion

- changelogs/next.md
- tartiflette/directive/builtins/non_introspectable.py
- tartiflette/schema/introspection.py
- tartiflette/schema/schema.py
- tests/functional/regressions/test_issue92.py
- tests/functional/test_introspection.py
- tests/functional/test_introspection_schema.py
> Update nonIntrospectable builtIn directive to be used on Schema SDL Object

- changelogs/next.md
- tartiflette/engine.py
- tests/functional/regressions/test_issue453.py
> ISSUE-453 - Handle errors during schema_directive_execution

- CHANGELOG.md
- changelogs/1.3.1.md
- changelogs/next.md
- setup.py
> Prepare 1.3.1 Release

- README.md
- tartiflette/language/parsers/libgraphqlparser/parser.py
Closes https://github.com/tartiflette/tartiflette/issues/483
> Add LIBGRAPHQLPARSER_DIR environmental variable

- CHANGELOG.md
- CONTRIBUTORS.md
- changelogs/1.3.3.md
- setup.py
> Prepare 1.3.3 release

- CHANGELOG.md
- changelogs/1.4.0.md
- changelogs/next.md
- setup.py
* Diff [1.3.3 vs master](https://github.com/tartiflette/tartiflette/compare/1.3.3...master)
> Release version 1.4.0

- .github/workflows/push_on_master.yml
- Makefile
> Require `PublishSdist` on `PublishWheels` in `push_on_master` workflow

- tests/functional/regressions/test_parent_concurrently.py
Fix `test_issue_xxx_concurrently_schema_level` test that has been randomly failing by sleeping based on the length of the field name.
This ensures that we correctly test that fields are resolved concurrently in the same order everytime.
Also update `test_issue_xxx_sequentially_schema_level` test to match more closely what we test in `test_issue_xxx_concurrently_schema_level`.
> Fix parent concurrently test

- .pylintrc
- CHANGELOG.md
- CONTRIBUTORS.md
- changelogs/1.4.1.md
- changelogs/next.md
- setup.cfg
- tartiflette/utils/directives.py
> Prepare 1.4.1 release
