tartiflette/tartiflette

tartiflette/parser/cffi/__init__.py, tartiflette/parser/visitor.py, tartiflette/schema/schema.py, tests/functional/test_mutations.py
The goal of this PR is to deduct the actual operation type for each root node and fix mutations resolve.
Before, if the GraphQL type of the parent node wasn't deductible, we would fallback to the `Query` type. However, this makes impossible to resolve mutations and other operation types. From now, the operation type is deduced using the OperationDefinition.
=> Retrieve the appropriate operation type with operation definition

CHANGELOG.md, setup.py, tartiflette/executors/basic.py, tartiflette/parser/cffi/__init__.py, tartiflette/parser/nodes/field.py, tartiflette/parser/visitor.py, tests/functional/test_alias.py, tests/functional/test_mutations.py
Now a query like 
```graphql
query aquery { anAlias: field }
```
will return
```
{"data": { "anAlias": "aData" } }
```
=> Add support for alias in Queries and Mutations

CHANGELOG.md, tartiflette/parser/cffi/__init__.py, tartiflette/parser/visitor.py, tests/functional/test_empty_value.py, tests/functional/types/exceptions/test_tartiflette_errors.py, tests/functional/types/test_enum.py, tests/functional/types/test_object.py, tests/functional/types/test_scalar.py
* b03b2877222d2afcf6b6894d4e62a3ba628faaa7 Removes replacement of breaking lines in order to parse the raw GraphQL query and have the correct locations on errors
* 1d61cfcd56167df3bde1440f0258cfa0b7ab6cd8 Re-raise `UnknownSchemaFieldResolver` if no `_inline_fragment_type` or cast it to a string if set to avoid any `TypeError` exception
* 5d98fd6658d257cc1da46f2d9aa1f09bf6986259 Adds manually `path` & `locations` attributes to the `Unknown SchemaFieldResolver` raised exception
=> Some fixes & improvements

CHANGELOG.md, tartiflette/engine.py, tartiflette/executors/basic.py, tartiflette/parser/cffi/__init__.py, tartiflette/parser/nodes/field.py, tartiflette/parser/parser.py, tartiflette/parser/visitor.py, tartiflette/resolver/factory.py, tartiflette/types/exceptions/tartiflette.py, tests/functional/regressions/test_issue21.py, tests/unit/executor/test_basic.py, tests/unit/parser/nodes/test_node_field.py, tests/unit/parser/test_parser.py, tests/unit/parser/test_visitor.py, tests/unit/test_engine.py, tests/unit/types/test_exceptions.py
The goal here is to be able to throw custom exceptions on our resolvers. Those exceptions could override the default `GraphQLError` behavior of `Tartiflette`. The only requirement for those custom exceptions should be to implement a `coerce_value` callable attribute.
This way, we could implement some custom exceptions that could have a custom coerced value:
```python
class BadRequestError(Exception):
def coerce_value(self, *_args, path=None, locations=None, **_kwargs):
return {"message": "Bad request", "type": "bad_request"}
@Resolver("Query.hello")
async def resolver_hello(parent, args, ctx, info):
if args["name"] == "":
raise BadRequestError("`name` argument shouldn't by empty.")
return "hello " + args["name"]
```
Following query:
```graphql
query {
hello(name: "")
}
```
Should result …
=> Handle custom exception errors

CHANGELOG.md, tartiflette/parser/cffi/__init__.py, tests/functional/regressions/test_issue71.py
Parsing errors must only live for the duration of the request.
Closes #71
=> Fix parsing error lifecycle

CHANGELOG.md, setup.py, tests/functional/conftest.py, tests/functional/data/sdls/animals.sdl, tests/functional/data/sdls/libraries.sdl, tests/functional/regressions/test_issue86.py, tests/functional/regressions/test_issue87.py, tests/functional/test_alias.py, tests/functional/test_queries.py
This PR introduce a new way to write functional tests by using all the power of `pytest`.
The goal is to declare Tartiflette schemas once at `conftest.py`:
https://github.com/dailymotion/tartiflette/blob/b9de1bd08b08dd03ff0a72a2097ecb4fdadb2026/tests/functional/conftest.py#L17-L21
Each deaclared schemas will generate its own Tartiflette engine. Then, you'll be able to inject those engine on your tests by decorating them with `@pytest.mark.ttftt_engine`.
This marker accepts two optional parameter:
* `name`: which define what schema to use (default is...  `default`)
* `resolvers`: a dict of resolvers to add to the engine
For instance:
```python
_SCHEMAS = {
"default": "path/to/my/schema.sdl",
"custom_engine": "path/to/my/custom/schema.sdl",
}
```
```python
@pytest.mark.asyncio …
```
=> Improve functional test with a custom pytest marker

CHANGELOG.md, tartiflette/engine.py, tartiflette/executors/basic.py, tests/functional/regressions/test_issue119.py, tests/unit/executor/test_basic.py
=> Add an "initial_value" parameter on the "execute"'s engine method

CHANGELOG.md, setup.py, tartiflette/types/argument.py, tartiflette/types/input_object.py, tartiflette/utils/arguments.py, tests/functional/regressions/test_issue133.py, tests/unit/utils/test_arguments.py
Directives on arguments are only applied on the first-level of arguments. If you do have a "complex" arguments composed of `InputObjectType` they will not be applied on them.
The goal if this PR is to fix this behavior and apply directives on each levels.
=> Apply directives on sub-levels arguments

CHANGELOG.md, tartiflette/types/exceptions/__init__.py, tartiflette/types/exceptions/tartiflette.py, tests/functional/regressions/test_pr155.py, tests/unit/types/test_exceptions.py
Hey guys, as discussed on Slack here is a proposal to add support for the `extensions` field on errors and simplify exceptions import & usage.
From the commit log:
the spec allows for an 'extensions' field on response errors:
https://github.com/facebook/graphql/blob/master/spec/Section%207%20--%20Response.md#errors
this adds this field into the generic GraphQLError exception so that
users can simply add their own extended information to their error exceptions
example usage:
```
from tartiflette.types.exceptions import GraphQLError
class WebserviceError(GraphQLError):
def __init__(self, message, extensions={}) -> None:
super().__init__(
message=message,
extensions=extensions
)
```
=> Add errors extensions support

tartiflette/schema/schema.py
This removes old unused placeholders in the schema `__init__` method.
=> Removed old placeholders

docs/tutorial/write-your-resolvers.md
---
All resolver functions were named the same in the query resolvers code snippet. I realized this when pylint complained and I don't think it was intentional. :-)
=> Docs: fix name of query resolver functions

CHANGELOG.md, Makefile, README.md, docker-compose.yml
Add the ability to launch the documentation website locally with the `/docs` folder, to simplify the contributing process for the documentation.
Only one command to launch the documentation on `http://localhost:3000`
```bash
make run-docs
```
ISSUE #165
=> Run the documentation website locally

docs/tutorial/create-server.md, docs/tutorial/extend-with-directives.md, docs/tutorial/project-initialization.md, docs/tutorial/running-a-query.md, docs/tutorial/write-your-mutation-resolvers.md, docs/tutorial/write-your-resolvers.md
The tutorial references "ingredients quantity" which I think is quite confusing: currently, an ingredient quantity has an ID, a name and a *quantity*… This PR suggests to simply use "ingredients".
May conflict with #166 b/c of the new function resolver name.
=> Docs: rename 'ingredients quantity' to 'ingredients'

CHANGELOG.md, changelogs/0.8.0.md, setup.py, tartiflette/parser/nodes/field.py, tartiflette/resolver/factory.py, tests/functional/regressions/test_issue199.py, tests/unit/resolver/test_factory.py, tests/unit/resolver/test_factory__resolver_executor.py, tests/unit/types/test_field.py
=> Executable directives on fields only wraps field resolvers at execution time

changelogs/0.9.0.md, setup.py, tartiflette/engine.py, tartiflette/resolver/factory.py, tests/unit/executor/test_basic.py, tests/unit/test_engine.py
The `error_coercer` signature changed from `Callable[[Exception]] -> dict` to `Callable[[Exception], dict] -> dict`.
The main idea of this change is to avoid calling the coerce_value himself within its own error_coercer implement, as this call must be executed by the engine.
Here are 2 examples of a custom error_coercer, the first one with the old way and the second one with the new way.
*Old way*
```python
from myvender import CustomException
from tartiflette.engine import Engine
from tartiflette.resolver.factory import default_error_coercer
def my_custom_error_coercer(exception):
error = default_error_coercer(exception)
if isinstance(exception, CustomException):
error["customfield"] = "blabla"
return error
engine = Engine(
error_coercer=my_custom_error_coercer
)
```
**New way** …
=> Error handling: change the 'error_coercer' signature

tartiflette/directive/directive.py, tartiflette/engine.py, tartiflette/scalar/custom_scalar.py, tests/unit/directives/test_directive.py
Fix a compatibility issue with the new Plugin API.
Now Directive/Scalar decorators supports instance or classes.
=> Support instance or class in decorator

CHANGELOG.md, changelogs/0.12.4.md, setup.py, tartiflette/parser/visitor/visitor.py, tests/functional/regressions/test_issue270.py
fix #270 
I use `# pylint: disable=unidiomatic-typecheck` and `type` because of :
```
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = True
>>> isinstance(a, int)
True
>>> 
```
Only `int` should be allowed as Float.
All this is wiil be done correctly in 1.x.x (which is near to being ready soon)
=> ISSUE-270: Consider Int var Values as valid Float

README.md, changelogs/1.0.0.md, tests/functional/coercers/test_coercer_string_field.py, tests/functional/regressions/test_multiline_strings.py
Cause we want the support of multiline string ("""example""") as litteral input value.
=> Update libgraphqlparser to latest master

.github/workflows/push.yml, .github/workflows/push_on_master.yml, CHANGELOG.md, Dockerfile, Makefile, changelogs/1.1.1.md, changelogs/next.md, setup.py
closes #301 
With this PR, ctypegen is no more needed for us.
Only python 3 is required to generated the .h files (but this is useless for us too, I'm thinking about removing it too). 
If I have more time later I'll do an "optionnable" thing so it'll be more easily mainlined.
@florimondmanca I'll ping you with a `test.pypi.org/simple` lib when it'll be ready so you could test it.
=> Upgrade Libgraphqlparser to python3 only version

changelogs/1.2.0.md
1.2.0 introduced a way to provide a custom arguments coercer. The `CHANGED` entry in the changelog is a bit misleading, as it could make people think that the default behaviour has changed, whereas the default is the same, and the feature is already documented in the `ADDED` part or the changelog.
=> Remove reference to coercer in CHANGED changelog of 1.2.0

tartiflette/coercers/outputs/abstract_coercer.py, tartiflette/types/object.py, tartiflette/types/union.py, tests/functional/regressions/test_issue381.py
closes #381 
The idea is to calls the coercion of the runtimeType when union complete object is done. 
It does some reg, on 4 tests that I will investigate, but maybe @Maximilien-R you can already give me feedbacks on it, if you think its not to stupid.
Coercing the Union -> complete the object -> coerce_the_object (maybe it will call complete object to much :/) -> call the directive on the object. I don't know if I'm really clear on this @Maximilien-R ?
I'll continue to dive In.
=> ISSUE-381, find a way to call post_out on type when they are accessed via a Union.

tartiflette/coercers/outputs/abstract_coercer.py, tartiflette/coercers/outputs/directives_coercer.py, tartiflette/coercers/outputs/enum_coercer.py, tartiflette/schema/schema.py, tartiflette/schema/transformer.py, tartiflette/types/enum.py, tartiflette/types/interface.py, tartiflette/types/object.py, tartiflette/types/scalar.py, tartiflette/types/union.py, tartiflette/utils/directives.py, tests/functional/regressions/issue278/test_issue278_extend_enum.py, tests/functional/regressions/issue278/test_issue278_extend_object.py, tests/functional/regressions/issue278/test_issue278_extend_scalar.py, tests/functional/regressions/test_input_directives.py, tests/functional/regressions/test_issue223.py, tests/functional/regressions/test_issue233.py, tests/functional/regressions/test_issue381.py, tests/functional/test_directives_went_through.py
As it was done with https://github.com/tartiflette/tartiflette/pull/430 for post input coercion, the goal of this PR is to provide more granular directive hooks for the pre output coercion with a fallback on the existing `on_pre_output_coercion` hook.
Also, as done for post input coercion, the prototype has been changed in order to provide the output type definition node:
```diff
@Directive("myDirective")
class MyDirective:
@staticmethod
async def on_pre_output_coercion(
directive_args,
next_directive,
+        output_definition_node,
value,
ctx,
):
pass
```
=> [v2] Improve pre output coercion directive hooks

tartiflette/language/ast/enum_type_definition.py, tartiflette/language/ast/enum_type_extension.py, tartiflette/language/ast/input_object_type_definition.py, tartiflette/language/ast/input_object_type_extension.py, tartiflette/language/ast/interface_type_definition.py, tartiflette/language/ast/interface_type_extension.py, tartiflette/language/ast/object_type_definition.py, tartiflette/language/ast/object_type_extension.py, tartiflette/language/ast/scalar_type_definition.py, tartiflette/language/ast/scalar_type_extension.py, tartiflette/language/ast/union_type_definition.py, tartiflette/language/ast/union_type_extension.py, tartiflette/schema/transformer.py, tartiflette/types/enum.py, tartiflette/types/input_object.py, tartiflette/types/interface.py, tartiflette/types/object.py, tartiflette/types/scalar.py, tartiflette/types/union.py, tests/unit/types/test_extend_definition.py
The goal of this PR is to extend the `definition` node from GraphQL types at extensions baking process. This will allow to have to complete definition node on directives hooks.
Also, there is a fix on `GraphQLEnumType` and `GraphQLUnionType` where we didn't set some values as list per default which could lead to errors at extensions bake if the type definition didn't mentions enum values/types:
```graphql
enum MyEnum
extend enum MyEnum { # Would raise TypeError (None doesn't have extend method)
VALUE
}
type Foo {
id: ID!
}
type Bar {
id: ID!
}
union MyUnion
extend union MyUnion = Foo | Bar # Would raise TypeError (None doesn't have extend method)
```
=> [v2] Extends GraphQL types definition nodes at extensions bake

tartiflette/__init__.py, tartiflette/coercers/outputs/compute.py, tartiflette/coercers/outputs/list_coercer.py, tartiflette/engine.py, tartiflette/resolver/resolver.py, tartiflette/schema/bakery.py, tartiflette/schema/schema.py, tartiflette/subscription/subscription.py, tartiflette/types/field.py, tests/functional/regressions/issue278/test_issue457.py
=> ISSUE-457 - Improve performance for I/O bound list resolvers by using parallel execution

CHANGELOG.md, changelogs/1.3.0.md, docs/api/engine.md, docs/api/resolver.md, docs/api/subscription.md, setup.py
=> Release 1.3.0

MANIFEST.in, changelogs/next.md
I am using Tartiflette for one of my projects and want to run the `mypy` type checker. In order to do this, the `py.typed` file needs to exist, as specified by [PEP-561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information).
I have confirmed that the file exists when creating an `sdist` and a wheel.
=> Expose types to downstream packages

.github/workflows/codeql-analysis.yml, .github/workflows/on_pull_requests.yml, .github/workflows/push_on_master.yml, Makefile
Simplify GitHub Actions workflows to use native actions.
Merge macOS and Linux tests together in Actions to simplify pull requests workflow.
Another PR will be made later to support building wheels on pull requests (and if it works as expected, on releases later on), so for now this PR leaves a few jobs mostly untouched, as they may completely change later.
Note: Pushing to test pypi seems to be broken, but other PRs are failing too (maybe the token is not valid anymore?).
---
=> Simplify GitHub actions workflows

.github/workflows/on_pull_requests.yml, Makefile, setup.py
Build wheels for macOS and Linux using `cibuildwheel` on pull requests.
This uses a "fake" extension to ensure that we build platform dependant wheels instead of pure Python ones (as libgraphqlparser build different files).
Another potential way to do this would be to provide a distclass with an `has_ext_modules` method returning `True`, but `auditwheel` library used by `cibuildwheel` wasn't so happy with it.
Known issues:
- As we have 3 different workers building packages (sdist, macOS wheels and Linux wheels), the timestamp used to define the dev version is not the same. I didn't find a proper way to handle this, apart from doing a modulo to have a minute/hour granularity on the timestamp, but if you think it's important to have this, we can discuss about a solution.
Note: For now, we …
=> Add wheels support for macOS and Linux

setup.py, tartiflette/engine.py, tartiflette/schema/builtins/introspection.py, tartiflette/schema/registry.py, tests/unit/test_resolver_decorator.py, tests/unit/test_schema_unit.py
On future version of python, open will use UTF-8 as a default and not the system prefered one. So I'd like to offer the capability to user to specify at Init/cook time the encoding of their SDL file (we'll use default system one per default if value is None).
=> Allow for specifing SDL file encoding (or rely on locale.getprefferedencoding(False))

changelogs/next.md, setup.py
It looks like `tartiflette` unnecessarily depends on `pytz`, which is not used in the codebase.
For reference, it was added [here](https://github.com/tartiflette/tartiflette/pull/88/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R89) at the time.
=> Remove unused `pytz` dependency

tartiflette/language/parsers/lark/transformers/token_transformer.py, tests/functional/conftest.py, tests/unit/conftest.py, tests/unit/language/parsers/lark/test_strings_parser.py
Replace some deprecated usages:
- `lark-parser`: `Token.pos_in_stream` -> `Token.start_pos` (deprecated in 0.12.0, [reference](https://github.com/lark-parser/lark/commit/2409065529f447ee12c77d015e02eefc6ceb8f5d#diff-590aa22e2712d270f8ec66a63ef40f0bc75bb564f20d59d854b207dcb704fee3R151-R154))
- `pytest`: `yield_fixture` -> `fixture` (deprecated in 6.2.0, [reference](https://docs.pytest.org/en/6.2.x/changelog.html#pytest-6-2-0-2020-12-12))
=> Fix some deprecation warnings

changelogs/next.md, tartiflette/__init__.py, tartiflette/engine.py
Follow up on https://github.com/tartiflette/tartiflette/pull/522
- Add `sdl_file_encoding` to `create_engine`, so that it is iso with `Engine`
- Few typos
- Add a changelog entry
=> Improvements over file encoding feature

.github/workflows/codeql-analysis.yml
As reported by GitHub Actions ([example](https://github.com/tartiflette/tartiflette/actions/runs/1269855444)):
- remove obsolete `git checkout HEAD^2`
- init submodules so that `tartiflette` can correctly be built from source
=> Fix CodeQL analysis workflow

Makefile, pyproject.toml, setup.cfg, setup.py
Define package metadata and requirements in `setup.cfg`, with regards to [setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html), allowing to have declarative configuration which should be easier to maintain.
Tested in https://github.com/mkniewallner/tartiflette/pull/5, with the source published [here](https://test.pypi.org/project/tartiflette-wheels/1.4.0.dev1632517466/).
Taking the occasion to add `python_requires` and `project_urls` to the metadata, in order to have link to issues, source code, changelog and documentation directly from PyPI.
`tests_require` is …
=> Use `setup.cfg` to define most package metadata

tartiflette/language/parsers/lark/transformers/token_transformer.py, tartiflette/language/validators/query/fragment_must_be_used.py, tartiflette/language/validators/query/fragment_spread_target_defined.py, tartiflette/language/validators/query/required_arguments.py, tartiflette/types/object.py, tests/functional/coercers/common.py, tests/functional/directives/test_directives_on_schema_subscription.py, tests/functional/regressions/test_directives_arguments.py, tests/functional/utils.py, tests/unit/test_introspection.py
Before submitting your pull request, make sure the following is done.
=> Refactor Code Expression ✨

changelogs/next.md, setup.cfg
`lark-parser` [reached version 1.0.0](https://github.com/lark-parser/lark/releases/tag/1.0.0) on November 2021.
None of the breaking changes appears to impact the codebase, but the package is now published as [`lark`](https://pypi.org/project/lark/#history) on PyPi instead of [`lark-parser`](https://pypi.org/project/lark-parser/#history).
Instead of pinning a specific version like we currently do, this PR also relaxes the requirement by allowing any `1.x` minor version.
This would mostly be beneficial for projects having multiple dependencies that depend on `lark`.
We might also consider not setting any upper bound constraint at all, like a lot of projects recently started to do (see [this …
=> Depend on `lark>=1.0.0`
